name: CICD

on:
  push:
    branches:
      - main

jobs:

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt

      - name: run tests
        working-directory: ./backend
        run: pytests || true

      - name: build backend image
        run: docker build -t my-api ./backend

      - name: build frontend image
        run: docker build -t my-react-app ./frontend



